# Uncomment the next line to define a global platform for your project
source 'https://cdn.cocoapods.org/'

platform :ios, '14.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  # Pods for TMadeCrochet
  pod 'YouTubePlayer'
  pod 'Google-Mobile-Ads-SDK'
end

target 'TMadeCrochet' do
  shared_pods
  
  target 'TMadeCrochetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TMadeCrochetUITests' do
    # Pods for testing
  end
end

post_install do |installer|
  installer.aggregate_targets.each do |target|
    target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
        xcconfig_path = config.base_configuration_reference.real_path
        IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end

